services:
  audiobookshelf:
    container_name: audiobookshelf
    image: ghcr.io/advplyr/audiobookshelf:${IMAGE_TAG:?IMAGE_TAG is required}
    restart: unless-stopped
    environment:
      - TZ=${TZ_LOCATION:?TZ_LOCATION is required}
    volumes:
      - ${DATA_LOCATION:?DATA_LOCATION is required}/config:/config
      - ${DATA_LOCATION:?DATA_LOCATION is required}/metadata:/metadata
      - ${DATA_LOCATION:?DATA_LOCATION is required}/audiobooks:/audiobooks
      - ${DATA_LOCATION:?DATA_LOCATION is required}/podcasts:/podcasts
    networks:
      - audiobookshelf_network
      - cloudflared_network
networks:
  audiobookshelf_network:
    driver: bridge
  cloudflared_network:
    external: true
