services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_IMAGE_TAG:?IMMICH_IMAGE_TAG is required}
    restart: unless-stopped
    volumes:
      - ${IMMICH_UPLOAD_LOCATION:?IMMICH_UPLOAD_LOCATION is required}:/data
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 2283:2283
    depends_on:
      - immich_redis
      - immich_postgres
    healthcheck:
      disable: false
  immich_redis:
    container_name: immich_redis
    image: docker.io/valkey/valkey:${IMMICH_REDIS_IMAGE_TAG:?IMMICH_REDIS_IMAGE_TAG is required}
    restart: unless-stopped
    healthcheck:
      test: redis-cli ping || exit 1
  immich_postgres:
    container_name: immich_postgres
    image: ghcr.io/immich-app/postgres:${IMMICH_POSTGRES_IMAGE_TAG:?IMMICH_POSTGRES_IMAGE_TAG is required}
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${IMMICH_POSTGRES_PASSWORD:?IMMICH_POSTGRES_PASSWORD is required}
      POSTGRES_USER: ${IMMICH_POSTGRES_USER:?IMMICH_POSTGRES_USER is required}
      POSTGRES_DB: ${IMMICH_POSTGRES_DB:?IMMICH_POSTGRES_DB is required}
      POSTGRES_INITDB_ARGS: '--data-checksums'
      DB_STORAGE_TYPE: HDD
    volumes:
      - ${IMMICH_POSTGRES_LOCATION_DATA:?IMMICH_POSTGRES_LOCATION_DATA is required}:/var/lib/postgresql/data
    shm_size: 128mb
    healthcheck:
      disable: false
