services:
  cloudflared:
    container_name: cloudflared
    image: cloudflare/cloudflared:${IMAGE_TAG:?IMAGE_TAG is required}
    restart: unless-stopped
    command: tunnel --no-autoupdate run --token ${TUNNEL_TOKEN:?TUNNEL_TOKEN is required}
    networks:
      - cloudflared_network
      - portainer_network
networks:
  cloudflared_network:
    name: cloudflared_network
    driver: bridge
  portainer_network:
    external: true
