services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:${PORTAINER_IMAGE_TAG:?PORTAINER_IMAGE_TAG is required}
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${PORTAINER_UPLOAD_LOCATION:?PORTAINER_UPLOAD_LOCATION is required}:/data
    ports:
      - 9443:9443
      - 9000:9000
networks:
  cloudflared_network:
