services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:${PORTAINER_IMAGE_TAG:?PORTAINER_IMAGE_TAG is required}
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${PORTAINER_UPLOAD_LOCATION:?PORTAINER_UPLOAD_LOCATION is required}:/data
    networks:
      - portainer_network
    security_opt:
      - no-new-privileges:true
    ports:
      - 127.0.0.1:9443:9443
networks:
  portainer_network:
    name: portainer_network
    driver: bridge
