services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:lts
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${UPLOAD_LOCATION}:/data
    ports:
      - 9443:9443
      - 9000:9000
networks:
  default:
    name: cloudflared_network
